### ISSUE TITLE
Some results are NA

### ISSUE THREAD

**Issue by Wanghair** [covidestim/covidestim#12]
Hello! I have some questions.
When I run cfg <- covidestim(nweeks = 31, region = 'Connecticut', pop_size = get_pop('Connecticut')) +
  input_cases(example_ct_data('cases')) +
  input_deaths(example_ct_data('deaths')) + 
  input_boost(example_ct_data('boost')) +
  input_hosp(example_ct_data('hospi')) 
some results are NA, for example immunoexposed_cumulative,  effective_protection_inf_vax_boost_prvl and so on.
How can I get these results?

Thank you !

**Comment by fayetteklaassen** [comment]
Hi, Thanks for your question, and it is correct that these results are NA.
The outcomes you mention are actually not computed in the current version of the model, but placeholders for intended future output variables.
