### ISSUE TITLE
Typo on covidestim.org

### ISSUE THREAD

**Issue by jacobwood27** [covidestim/covidestim#6]
There is a small typo on the county statistics page:

Percent Ever Infected
Percent ever infected is our estimate of the number of individuals in the county or state **popululation** who have been infected at least once with COVID-19.

**Comment by marcusrussi** [comment]
Thanks Jacob! Fix should be live in 30 minutes.

-Marcus

**Comment by jacobwood27** [comment]
Quick work Marcus!
